const { chromium } = require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
;(async () => {
  const browser = await chromium.launch({headless:true})
  const page = await browser.newPage({viewport:{width:1280,height:900}})
  page.on('close',()=>console.log('PAGE_CLOSED'))
  page.on('crash',()=>console.log('PAGE_CRASHED'))
  page.on('console',(m)=>console.log('CONSOLE',m.type(),m.text()))
  page.on('pageerror',(e)=>console.log('PAGEERROR',e.message))
  await page.goto('http://127.0.0.1:4191/components/lxtreeselect',{waitUntil:'networkidle'})
  console.log('before screenshot closed=',page.isClosed())
  await page.screenshot({path:'.impeccable/critique/wave6-tree-cascader-2026-09-30/assessment-b/test-before.png',fullPage:true})
  console.log('after screenshot closed=',page.isClosed())
  await page.evaluate(()=>{const s=document.createElement('script');s.src='http://127.0.0.1:8411/detect.js?test=1';document.head.appendChild(s)})
  await page.waitForTimeout(2200)
  console.log('before second screenshot closed=',page.isClosed())
  await page.screenshot({path:'.impeccable/critique/wave6-tree-cascader-2026-09-30/assessment-b/test-after.png',fullPage:true})
  console.log('after second screenshot closed=',page.isClosed())
  await browser.close()
})().catch(e=>{console.error(e.stack||e);process.exitCode=1})