const fs = require('node:fs/promises')
const path = require('node:path')
const { chromium } = require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
;(async () => {
 const outputDir=path.resolve('.impeccable/critique/wave6-tree-cascader-2026-09-30/assessment-b'); const screenshotDir=path.join(outputDir,'screenshots'); await fs.mkdir(screenshotDir,{recursive:true})
 const browser=await chromium.launch({headless:true}); const page=await browser.newPage({viewport:{width:1280,height:900}})
 page.on('close',()=>console.log('closed')); page.on('crash',()=>console.log('crash')); page.on('pageerror',e=>console.log('error',e.message))
 const requests=[]; page.on('request',r=>requests.push(r.url())); const logs=[]; page.on('console',m=>logs.push({type:m.type(),text:m.text()}))
 await page.goto('http://127.0.0.1:4191/components/lxtreeselect',{waitUntil:'networkidle'}); await page.waitForTimeout(300)
 console.log('before inject',page.isClosed())
 const injection=await page.evaluate(()=>{document.title='[Human]';const s=document.createElement('script');s.src='http://127.0.0.1:8411/detect.js?x=1';document.head.appendChild(s);return {src:s.src}})
 await page.waitForTimeout(2200); console.log('after inject',page.isClosed())
 const state=await page.evaluate(()=>({w:window.innerWidth,scroll:document.documentElement.scrollWidth}))
 console.log('before shot',page.isClosed(),JSON.stringify(state))
 await page.screenshot({path:path.join(screenshotDir,'minimal.png'),fullPage:true}); console.log('after shot',page.isClosed())
 await fs.writeFile(path.join(screenshotDir,'minimal.console.json'),JSON.stringify(logs,null,2)); await fs.writeFile(path.join(screenshotDir,'minimal.requests.json'),JSON.stringify(requests,null,2)); await fs.writeFile(path.join(screenshotDir,'minimal.meta.json'),JSON.stringify({state,injection},null,2))
 await browser.close()
})().catch(e=>{console.error(e.stack||e);process.exitCode=1})